### ISSUE TITLE
Создать первичную структуру проекта

### ISSUE THREAD

**Issue by HuntMark** [HuntMark/tatbash-bot#1]
На базе фреймворка Spring Boot.
Сборщик Maven.

**Comment by olzhas27** [comment]
на вебхуках будем делать?

**Comment by HuntMark** [comment]
что ты имеешь ввиду? поясни, плиз

**Comment by olzhas27** [comment]
ну насколько мне известно есть два способа реализации бота:
1) через опрос -  когда мы сами запрашиваем апдейты у сервера, обрабатываем их и отправляем свои апдейты серверу
2) на "вебхуках" - когда мы резервируем определенный url, по которому сервер будет сам дергать нас при каждом апдейте и получать наши апдейты

2ой способ вроде как требует наличия отдельного сервера, домена и SSL-сертификата

**Comment by HuntMark** [comment]
Я планирую использовать эту либу https://github.com/rubenlagus/TelegramBots. Там рекомендуется использовать Long Pooling. Думаю, его и будем использовать.

**Comment by HuntMark** [comment]
Эту задачу закрываю, так как эта автоматически создалась, на PR

**Comment by HuntMark** [comment]
Всё-таки переоткрыл :D, чтобы ссылаться на этот issue из PR
